# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'', max_length=200)),
                ('numVotes', models.IntegerField(default=0)),
                ('openForever', models.BooleanField(default=True)),
                ('dayLimit', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('startTimeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'', max_length=200)),
                ('pollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.CharField(default=b'', max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
                ('category', models.CharField(default=b'', max_length=200)),
                ('avRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('numReviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(default=b'', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=b'', max_length=200)),
                ('userVerified', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollChoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.PollChoice')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Topic'),
        ),
        migrations.AddField(
            model_name='review',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.UserProfile'),
        ),
        migrations.AddField(
            model_name='poll',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.UserProfile'),
        ),
    ]
