# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 21:27
from __future__ import unicode_literals

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='startTimeStamp',
        ),
        migrations.AddField(
            model_name='tag',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
