# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pollID',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Poll'),
            preserve_default=False,
        ),
    ]
