# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0002_auto_20171009_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Topic'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='pollChoiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.PollChoice'),
        ),
    ]
