# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0002_auto_20171014_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='alltags',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Tag'),
        ),
        migrations.AddField(
            model_name='alltags',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Topic'),
        ),
    ]
