# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0002_auto_20171012_0232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('userID', 'topicID')]),
        ),
    ]
