# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0002_auto_20171106_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
