# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0003_auto_20171106_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltags',
            name='type',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
