# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0003_auto_20171009_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userVerified',
            field=models.BooleanField(default=False),
        ),
    ]
