# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0003_auto_20171119_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
