# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0004_alltags_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllTags',
            new_name='TagLinker',
        ),
    ]
