# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0005_auto_20171120_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='pollID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Poll'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='reviewID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowItAllAPI.Review'),
        ),
    ]
