# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0005_auto_20171106_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
