# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowItAllAPI', '0006_auto_20171120_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='opinionTotal',
        ),
        migrations.AddField(
            model_name='review',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
